CREATE TABLE "TENANT_MAIL_SETTINGS" (
	"TENANT_ID" uuid PRIMARY KEY NOT NULL,
	"HOST" varchar(255) NOT NULL,
	"PORT" integer NOT NULL,
	"SECURE" boolean DEFAULT false NOT NULL,
	"USERNAME" varchar(255),
	"PASSWORD_ENCRYPTED" varchar(512),
	"FROM_EMAIL" varchar(255) NOT NULL,
	"FROM_NAME" varchar(255),
	"ENABLED" boolean DEFAULT true NOT NULL,
	"UPDATED_BY" uuid NOT NULL,
	"UPDATED_AT" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "TENANT_MAIL_SETTINGS" ADD CONSTRAINT "TENANT_MAIL_SETTINGS_TENANT_ID_TENANTS_ID_fk" FOREIGN KEY ("TENANT_ID") REFERENCES "public"."TENANTS"("ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "TENANT_MAIL_SETTINGS" ADD CONSTRAINT "TENANT_MAIL_SETTINGS_UPDATED_BY_USERS_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."USERS"("ID") ON DELETE cascade ON UPDATE no action;