CREATE TABLE "CONNECTOR_INSTANCES" (
	"ID" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"TENANT_ID" uuid NOT NULL,
	"CONNECTOR_TYPE" varchar(64) NOT NULL,
	"NAME" varchar(255) NOT NULL,
	"CONFIG" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"ENABLED" boolean DEFAULT true NOT NULL,
	"IS_DEFAULT" boolean DEFAULT false NOT NULL,
	"UPDATED_BY" uuid NOT NULL,
	"CREATED_AT" timestamp with time zone DEFAULT now() NOT NULL,
	"UPDATED_AT" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "CONNECTOR_INSTANCES" ADD CONSTRAINT "CONNECTOR_INSTANCES_TENANT_ID_TENANTS_ID_fk" FOREIGN KEY ("TENANT_ID") REFERENCES "public"."TENANTS"("ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CONNECTOR_INSTANCES" ADD CONSTRAINT "CONNECTOR_INSTANCES_UPDATED_BY_USERS_ID_fk" FOREIGN KEY ("UPDATED_BY") REFERENCES "public"."USERS"("ID") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "CONN_INST_TENANT_TYPE_IDX" ON "CONNECTOR_INSTANCES" USING btree ("TENANT_ID","CONNECTOR_TYPE");--> statement-breakpoint
CREATE UNIQUE INDEX "CONN_INST_TENANT_TYPE_NAME_IDX" ON "CONNECTOR_INSTANCES" USING btree ("TENANT_ID","CONNECTOR_TYPE","NAME");