-- P3 Session 9 — round-out of intermediate events.
--
-- New CONDITIONAL_SUBSCRIPTIONS table (mirrors MESSAGE_SUBSCRIPTIONS
-- shape; same row-shape lets the variable-set hook fan-out cheaply).
-- Five new audit event types. Everything idempotent.

CREATE TABLE IF NOT EXISTS "CONDITIONAL_SUBSCRIPTIONS" (
  "ID" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "TENANT_ID" uuid NOT NULL,
  -- Catch row: instance + token set, process null.
  -- Start row: process set, instance + token null.
  "INSTANCE_ID" uuid,
  "TOKEN_ID" uuid,
  "SCOPE_TOKEN_ID" uuid,
  "PROCESS_ID" uuid,
  -- FEEL expression evaluated against the instance (or fresh) variable
  -- bag. Stored as text — parsed at hook-fire time. Capped at 4 KB to
  -- catch obviously malformed input early.
  "CONDITION_EXPRESSION" varchar(4096) NOT NULL,
  "CREATED_AT" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "CONDITIONAL_SUBSCRIPTIONS_TENANT_FK"
    FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE CASCADE,
  CONSTRAINT "CONDITIONAL_SUBSCRIPTIONS_INSTANCE_FK"
    FOREIGN KEY ("INSTANCE_ID") REFERENCES "PROCESS_INSTANCES"("ID") ON DELETE CASCADE,
  CONSTRAINT "CONDITIONAL_SUBSCRIPTIONS_TOKEN_FK"
    FOREIGN KEY ("TOKEN_ID") REFERENCES "INSTANCE_TOKENS"("ID") ON DELETE CASCADE,
  CONSTRAINT "CONDITIONAL_SUBSCRIPTIONS_SCOPE_FK"
    FOREIGN KEY ("SCOPE_TOKEN_ID") REFERENCES "INSTANCE_TOKENS"("ID") ON DELETE CASCADE,
  CONSTRAINT "CONDITIONAL_SUBSCRIPTIONS_PROCESS_FK"
    FOREIGN KEY ("PROCESS_ID") REFERENCES "PROCESSES"("ID") ON DELETE CASCADE,
  CONSTRAINT "CONDITIONAL_SUBSCRIPTIONS_KIND_CHK" CHECK (
    ("TOKEN_ID" IS NOT NULL AND "INSTANCE_ID" IS NOT NULL AND "PROCESS_ID" IS NULL)
    OR
    ("TOKEN_ID" IS NULL AND "INSTANCE_ID" IS NULL AND "PROCESS_ID" IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS "CONDITIONAL_SUB_TENANT_IDX"
  ON "CONDITIONAL_SUBSCRIPTIONS" ("TENANT_ID");

CREATE INDEX IF NOT EXISTS "CONDITIONAL_SUB_INSTANCE_IDX"
  ON "CONDITIONAL_SUBSCRIPTIONS" ("INSTANCE_ID");

CREATE INDEX IF NOT EXISTS "CONDITIONAL_SUB_TOKEN_IDX"
  ON "CONDITIONAL_SUBSCRIPTIONS" ("TOKEN_ID");

CREATE INDEX IF NOT EXISTS "CONDITIONAL_SUB_PROCESS_IDX"
  ON "CONDITIONAL_SUBSCRIPTIONS" ("PROCESS_ID");

-- New audit-event types.
ALTER TYPE "public"."INSTANCE_EVENT_TYPE" ADD VALUE IF NOT EXISTS 'message-thrown';
ALTER TYPE "public"."INSTANCE_EVENT_TYPE" ADD VALUE IF NOT EXISTS 'link-followed';
ALTER TYPE "public"."INSTANCE_EVENT_TYPE" ADD VALUE IF NOT EXISTS 'conditional-subscribed';
ALTER TYPE "public"."INSTANCE_EVENT_TYPE" ADD VALUE IF NOT EXISTS 'conditional-satisfied';
ALTER TYPE "public"."INSTANCE_EVENT_TYPE" ADD VALUE IF NOT EXISTS 'conditional-unsubscribed';
